### ISSUE TITLE
exceptions System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by patil-nileshb** [Jericho/StrongGrid#254]
don't know if this is related to #248 but this is what I get sometimes.

`System.Net.Http.HttpRequestException: An error occurred while sending the request. 
---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Pathoschild.Http.Client.FluentClient.<SendImplAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Pathoschild.Http.Client.FluentClient.<<SendAsync>b__21_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Pathoschild.Http.Client.Retry.RetryCoordinator.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Pathoschild.Http.Client.Internal.Request.<Execute>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StrongGrid.Resources.Mail.<SendAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter``1.GetResult()
   at ThreeBirds.EmailProviders.SendGrid.SendGridProvider.CreateNewMessageInSendGrid(LogicalSendContext context, Recipient[] recipients, Boolean shouldMapEvents, String htmlContent, String textContent, String emailPipeSettingsJson, String defaultSendGridDomain, Boolean isPreviewEnvironment)`

this happens only few times. not always. 
sometimes on sendGridClient.Mail.SendAsync()
and sometimes on sendGridClient.SenderAuthentication.GetAllDomainsAsync()

so while using this, I tried setting 
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
            ServicePointManager.Expect100Continue = true;`
in constructor of a class which calls all these methods.

this is happening with 0.49.1 and happened in previous version too.

**Comment by Jericho** [comment]
`Could not create SSL/TLS secure channel` is an intermittent problem in the SendGrid API which has been reported to SendGrid but, to my knowledge, there is no resolution. This issue was reported [here](https://github.com/sendgrid/sendgrid-csharp/issues/100), [here](https://github.com/sendgrid/sendgrid-csharp/issues/214) and [here](https://github.com/sendgrid/sendgrid-csharp/issues/505).

As you can see from these other cases, SendGrid wants you to open a case with their support team in order to investigate this issue.

Let me know if they provide any resolution, I am curious.

**Comment by patil-nileshb** [comment]
thank you. I will do that.

**Comment by patil-nileshb** [comment]
response from sendgrid support - 

> We have seen this error before with other clients and in those cases, they were using old versions of .dll files. Is it possible that applies to you? There have been some updates to that library over the past few months and I know that some of our API calls have been updated and the newer library should reflect this. It may be worth making sure that your library is up to date so that we can make sure you're making the most up to date calls to SendGrid.
