### ISSUE TITLE
NullReference exception if pass BCC without TO to SendAsync

### ISSUE THREAD

**Issue by churupaha** [Jericho/StrongGrid#286]
Hi.

If I specify only BCC without TO and call SendAsync, it fails with NullReference exception, probably here

				personalization.To = personalization.To?
					.Distinct(emailAddressComparer)
					.ToArray();
				personalization.Cc = personalization.Cc?
					.Distinct(emailAddressComparer)
					.Except(personalization.To, emailAddressComparer)
					.ToArray();
				personalization.Bcc = personalization.Bcc?
					.Distinct(emailAddressComparer)
					.Except(personalization.To, emailAddressComparer)
					.Except(personalization.Cc, emailAddressComparer)
					.ToArray();

Is it possible to fix quickly? Because I'm thinking on forking it and make a custom nuget package for .net core :(

Thanx!

**Comment by churupaha** [comment]
Here is stack trace, it fails on

			personalization.Cc = personalization.Cc?
				.Distinct(emailAddressComparer)
				**.Except(personalization.To, emailAddressComparer)**
				.ToArray();
			personalization.Bcc = personalization.Bcc?
				.Distinct(emailAddressComparer)
				**.Except(personalization.To, emailAddressComparer)**
				.Except(personalization.Cc, emailAddressComparer)
				.ToArray();

System.ArgumentNullException: Value cannot be null.
Parameter name: second
   at System.Linq.Enumerable.Except[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)
   at StrongGrid.Resources.Mail.SendAsync(IEnumerable`1 personalizations, String subject, IEnumerable`1 contents, MailAddress from, MailAddress replyTo, IEnumerable`1 attachments, String templateId, IEnumerable`1 sections, IEnumerable`1 headers, IEnumerable`1 categories, IEnumerable`1 customArgs, Nullable`1 sendAt, String batchId, UnsubscribeOptions unsubscribeOptions, String ipPoolName, MailSettings mailSettings, TrackingSettings trackingSettings, CancellationToken cancellationToken)
   at GlobusAI.Dedicare.Backend.Services.ConversationsService.SendMessage(ConversationMessage message) in /home/carabao/Work/dedicare_be/GlobusAI.Dedicare.Backend/Services/ConversationsService.cs:line 97
   at GlobusAI.Dedicare.Backend.Controllers.ConversationsController.SendMessage(ConversationMessage message) in /home/carabao/Work/dedicare_be/GlobusAI.Dedicare.Backend/Controllers/ConversationsController.cs:line 33
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by Jericho** [comment]
At first glance looks like you’re right: Linq’s Except method does not like to be passed a null value. I’ll write a unit test to reproduce.

**Comment by churupaha** [comment]
Yep, exactly, the only quick fix I could suggest is 

.Except(personalization.To ?? new List<MailAddress>(), emailAddressComparer)

for both cases... oh, if you fix it, it will be so helpful.

The lib StrongGrid is incomparably better than the official one... that's why I use it.

**Comment by churupaha** [comment]
If you could provide ETA for this fix it will be great. I just don't know if I need to fix it on my side and have a 2nd nuget package... :)

**Comment by Jericho** [comment]
If I can reproduce the issue, I'll have a fix by the end of the day.

**Comment by churupaha** [comment]
I helped you little bit with full request containing the test with reproducing the bug and the fix.

**Comment by churupaha** [comment]
Big thanx, you approved it! When do you think you could deploy the updated nuget package? Because I use it from nuget.org :)

**Comment by Jericho** [comment]
It's being published to NuGet as we speak. Should be available within the next 30 minutes or so.

**Comment by churupaha** [comment]
You rock! Thanx!

**Comment by srutzky** [comment]
@Jericho (and @churupaha ) Thanks for fixing this! I am (soon to be "was") experiencing this as well. Though in my situation I have the "To" list filled out, but the "CC" list is empty. That still seems consistent with the problem being `Except` not liking the `null` as that condition would still fail on the following segment:

```csharp
.Except(personalization.Cc, emailAddressComparer)
```

of the `personalization.Bcc = personalization.Bcc?` line.

**Comment by Jericho** [comment]
@srutzky yes indeed you experienced the same problem. I’m glad that @churupaha and I already fixed it.

**Comment by srutzky** [comment]
@Jericho Yes, I can now confirm that this update did indeed fix it 😺 .
