### ISSUE TITLE
Connection exceptions on Contacts.ImportAsync

### ISSUE THREAD

**Issue by kbtahir** [Jericho/StrongGrid#295]
Hi, 

I've been using the Contacts.ImportAsync method to push data to sendgrid (update contacts data).  I've been trying to stay within the rate limits SendGrid wants but I am getting the following error periodically.  Each time i call this method I am sending 1000 contact records each with 100 customfields (large dataset).  Error is periodic, meaning sometimes the exact same call works successfully so I don't think i have a data or formatting problem.

1. Any suggestions on how to avoid this error?
2. How do I debug output the actual error coming from SendGrid?

Appreciate any help you can provide.
```
ERROR 
-----------------------------------
-		InnerException	{System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Security.SslStreamInternal.<WriteSingleChunk>g__CompleteAsync|36_1[TWriteAdapter](ValueTask writeTask, Byte[] bufferToReturn)
   at System.Net.Security.SslStreamInternal.WriteAsyncChunked[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Security.SslStreamInternal.<WriteAsyncInternal>g__ExitWriteAsync|35_0[TWriteAdapter](ValueTask task)
   at System.Net.Http.HttpConnection.WriteAsync(ReadOnlyMemory`1 source)
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Pathoschild.Http.Client.FluentClient.SendImplAsync(IRequest request)
   at Pathoschild.Http.Client.FluentClient.<SendAsync>b__21_0(IRequest req)
   at Pathoschild.Http.Client.Retry.RetryCoordinator.ExecuteAsync(IRequest request, Func`2 dispatcher)
   at Pathoschild.Http.Client.Internal.Request.Execute()
   at Pathoschild.Http.Client.Internal.Request.AsMessage()
   at StrongGrid.Utilities.Extensions.AsSendGridObject[T](IRequest request, String propertyName, JsonConverter jsonConverter)
   at sendgridconsole.Program.<>c__DisplayClass0_4.<<Main>b__2>d.MoveNext() in D:\tfsworkspace\Application\sendgrid\sendgridconsole\Program.cs:line 54}	System.Exception {System.Net.Http.HttpRequestException}
```

**Comment by Jericho** [comment]
You are not the first person to get the `connection was forcibly closed by the remote host` exception. It's discussed [here](https://github.com/sendgrid/sendgrid-csharp/issues/862).

One person has suggested the following line of C# code to solve the problem:
```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
```

My guess (and it's just a guess), is that SendGrid may have intermittent problems related to load balancing which could explain why some people experience this problem intermittently.

**Comment by kbtahir** [comment]
Thanks for the quick feedback.  I tried the suggestion above but still have same issues.

Sendgrid mentions in their documentation that any rate limit issues are provided in the response header.

How do I view the response header from SendGrid through the StrongGrid library? 

https://sendgrid.api-docs.io/v3.0/how-to-use-the-sendgrid-v3-api/api-rate-limits#rate-limit-response-header

**Comment by Jericho** [comment]
Do you have logging in your app? If so so can set the log level to Debug and StrongGrid will log requests and responses.

**Comment by kbtahir** [comment]
Thank You.  I will add logging to my app and try it out.

In terms of the connection issue, I was able to work around it by adding retry logic.   
(https://stackoverflow.com/questions/1563191/cleanest-way-to-write-retry-logic)

StrongGrid is a great library and thanks so much for your support!
