### ISSUE TITLE
Add IPPool to ProcessedEvent class

### ISSUE THREAD

**Issue by davidlouth** [Jericho/StrongGrid#314]
According to SendGrid doc: https://sendgrid.com/docs/for-developers/tracking-events/event/, the Processed event has a pool property:
```json
"pool": {
            "name": "new_MY_test",
            "id": 210
        },
```
It looks like ParseWebhookEvents accounts for "pool" and there's WebHooks\IPPool.cs with Name and ID but IPPool isn't part of any event class that I can find.

**Comment by Jericho** [comment]
You're right, `pool` is indeed in the documentation. It's possible that I missed it when I wrote the webhook event parser back in 2016 but I believe it's more likely that it was added to the documentation at a later date and never mentioned in SendGrid's release notes, therefore I never realized that it was added.

Thanks for pointing this out, I'll take care of it.

`<rant>`
The documentation page that you linked is notoriously riddled with confusing and sometimes contradictory information and attempts at clarifying it have gone unanswered. See:

https://github.com/Jericho/StrongGrid/issues/247
https://github.com/Jericho/StrongGrid/issues/248
https://github.com/sendgrid/sendgrid-csharp/issues/792
https://github.com/sendgrid/docs/issues/4865
`</rant>`

Sorry for the rant, I had to get this off my chest. I want StrongGrid's webhook parser to be accurate and it bothers me that we can't get help to fix the documentation when we find inaccurate or contradictory information.

**Comment by davidlouth** [comment]
Awesome, thanks.

Yeah, It seems like every time I look in their documentation, I discover something new or something that contradicts the reality of their api/webhook processing.

**Comment by MikeDoesStuff** [comment]
> ```
> "pool": {
>             "name": "new_MY_test",
>             "id": 210
>         },
> ```

Not sure how recent of a change this is but now Sendgrid posts the pool ID as a string rather than an Int - this causes an exception when Parsing.

```An unhandled exception has occurred while executing the request.
System.Text.Json.JsonException: The JSON value could not be converted to System.Int64. Path: $.pool.id | LineNumber: 0 | BytePositionInLine: 110.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'String' as a number.
   at System.Text.Json.Utf8JsonReader.TryGetInt64(Int64& value)
   at System.Text.Json.Utf8JsonReader.GetInt64()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)```

**Comment by Jericho** [comment]
@MikeDoesStuff I see you raised a new issue (#454) regarding this problem. Let's continue the discussion in that new issue rather than in this 2 year old issue.
