### ISSUE TITLE
Add "processing" Email Activity Status

### ISSUE THREAD

**Issue by toddca** [Jericho/StrongGrid#336]
Evidently "processing" is a valid EmailActivityStatus when calling into EmailActivities.SearchAsync()

Failed to get 20 message activities. Error=Error converting value "processing" to type 'StrongGrid.Models.EmailActivityStatus'. Path 'messages[9].status', line 1, position 2896.

Newtonsoft.Json.JsonSerializationException: Error converting value "processing" to type 'StrongGrid.Models.EmailActivityStatus'. Path 'messages[9].status', line 1, position 2896.

 ---> System.ArgumentException: Requested value 'processing' was not found.

   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)

   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)

**Comment by Jericho** [comment]
Thanks for pointing this out. Definitely need to add this missing status to our `EmailActivityStatus` enum.
