### ISSUE TITLE
Unable to write a value of type StrongGrid.Models.MailAddress

### ISSUE THREAD

**Issue by SeanFeldman** [Jericho/StrongGrid#410]
After upgrading to 0.87.0 the following exception is thrown w/o any code changes.

```
System.Exception: Unable to write a value of type StrongGrid.Models.MailAddress
System.MissingMethodException: Method not found: 'Void 
System.Text.Json.Serialization.Metadata.JsonObjectInfoValues`1.set_ObjectCreator(System.Func`1<!0>)'.
   at StrongGrid.Utilities.StrongGridJsonSerializerContext.get_MailAddress() 
```

.NET 6
Function v4
Isolated worker SDK 1.3.0

<details>
<summary>Stacktrace</summary>

<block>

[2022-02-04T07:43:39.955Z] Message processing error (Action=UserCallback, ClientId=MessageReceiver1Notifications, EntityPath=Notifications, Endpoint=redacted.servicebus.windows.net)
[2022-02-04T07:43:39.958Z] System.Private.CoreLib: Exception while executing function: Functions.NotificationProcessor. System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (Unable to write a value of type StrongGrid.Models.MailAddress)
[2022-02-04T07:43:39.960Z]  ---> System.Exception: Unable to write a value of type StrongGrid.Models.MailAddress
[2022-02-04T07:43:39.961Z]  ---> System.MissingMethodException: Method not found: 'Void System.Text.Json.Serialization.Metadata.JsonObjectInfoValues\`1.set_ObjectCreator(System.Func\`1<!0>)'.
[2022-02-04T07:43:39.962Z]    at StrongGrid.Utilities.StrongGridJsonSerializerContext.get_MailAddress()
[2022-02-04T07:43:39.963Z]    at System.Text.Json.JsonSerializerOptions.GetClassFromContextOrCreate(Type type)
[2022-02-04T07:43:39.964Z]    at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
[2022-02-04T07:43:39.965Z]    at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type runtimeType)
[2022-02-04T07:43:39.966Z]    at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue value, JsonSerializerOptions options)
[2022-02-04T07:43:39.967Z]    at StrongGrid.Utilities.StrongGridJsonObjectConverter.WriteValue(Utf8JsonWriter writer, Object value, JsonSerializerOptions options)
[2022-02-04T07:43:39.968Z]    --- End of inner exception stack trace ---
[2022-02-04T07:43:39.969Z]    at StrongGrid.Utilities.StrongGridJsonObjectConverter.WriteValue(Utf8JsonWriter writer, Object value, JsonSerializerOptions options)
[2022-02-04T07:43:39.970Z]    at StrongGrid.Utilities.StrongGridJsonObjectConverter.Write(Utf8JsonWriter writer, StrongGridJsonObject value, JsonSerializerOptions options)
[2022-02-04T07:43:39.973Z]    at System.Text.Json.Serialization.JsonConverter\`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
[2022-02-04T07:43:39.974Z]    at System.Text.Json.Serialization.JsonConverter\`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
[2022-02-04T07:43:39.975Z]    at System.Text.Json.Serialization.JsonConverter\`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
[2022-02-04T07:43:39.977Z]    at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
[2022-02-04T07:43:39.977Z]    at System.Text.Json.JsonSerializer.WriteUsingGeneratedSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
[2022-02-04T07:43:39.978Z]    at System.Text.Json.JsonSerializer.WriteStringUsingGeneratedSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
[2022-02-04T07:43:39.979Z]    at System.Text.Json.JsonSerializer.Serialize(Object value, Type inputType, JsonSerializerContext context)
[2022-02-04T07:43:39.980Z]    at StrongGrid.Resources.Mail.SendAsync(IEnumerable\`1 personalizations, String subject, IEnumerable\`1 contents, MailAddress from, IEnumerable\`1 replyTo, IEnumerable\`1 attachments, String templateId, IEnumerable\`1 headers, IEnumerable\`1 categories, IEnumerable\`1 customArgs, Nullable\`1 sendAt, String batchId, UnsubscribeOptions unsubscribeOptions, String ipPoolName, MailSettings mailSettings, TrackingSettings trackingSettings, MailPriority priority, CancellationToken cancellationToken)
[2022-02-04T07:43:39.981Z]    at Tva.Notifications.NotificationProcessor.HandleInvitationProcessStarted(InvitationProcessStarted message) in C:\github\TVA\Tva.Notifications\NotificationProcessor.InvitationProcessStarted.cs:line 83
[2022-02-04T07:43:39.982Z]    at Tva.Notifications.NotificationProcessor.Run(String rawEvent, Dictionary`2 userProperties, FunctionContext context) in C:\github\TVA\Tva.Notifications\NotificationProcessor.cs:line 42
[2022-02-04T07:43:39.983Z]    at Microsoft.Azure.Functions.Worker.Invocation.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker.Core\Invocation\VoidTaskMethodInvoker.cs:line 22

</block>

</details>

**Comment by Jericho** [comment]
Can you provide additional information to help me reproduce this problem? Any code snippet you can share? A public GitHub repo you can point me to? Any specific steps need to be taken to reproduce? Does this problem occur only in Azure function or are you able to reproduce when running the code locally on your machine?

I am able to successfully send myself test emails using the following code:
```csharp
var messageId = await client.Mail.SendAsync(personalizations, subject, new[] { textContent, htmlContent }, from,
	headers: headers,
	customArgs: customArgs,
	mailSettings: mailSettings,
	trackingSettings: trackingSettings,
	priority: MailPriority.High,
	cancellationToken: cancellationToken
).ConfigureAwait(false);
await log.WriteLineAsync($"Email has been sent. Message Id: {messageId}").ConfigureAwait(false);
```

so I suspect there must be something specific to your environment.

The big change that was introduced to 0.87.0 is that I removed the Newtonsoft JSON.NET dependency and replaced it with Microsoft's System.Text.Json. I'm not very familiar with the Azure function environment, but maybe there is something about it  that is not compatible with the Json serializer. I know this sounds like an egregious statement but [I have heard of such compatibility problems in Azure function environments before](https://github.com/Jericho/StrongGrid/issues/370). 

All this to say, let me know if you can run your code on your own machine. This would help us determine if the problem is localized to Azure functions or not.

**Comment by SeanFeldman** [comment]
@Jericho, I can't share the code but I can share the function code and configuration from the project.

**Azure Function (Service Bus trigger)**

```c#
public partial class NotificationProcessor
{
    private readonly StrongGridClient emailClient;
    private readonly SendgridOptions sendgridOptions;
    private readonly ILogger<NotificationProcessor> logger;

    public NotificationProcessor(StrongGridClient emailClient, SendgridOptions sendgridOptions, ILogger<NotificationProcessor> logger)
    {
        this.emailClient = emailClient;
        this.sendgridOptions = sendgridOptions;
        this.logger = logger;
    }
    
    [Function(nameof(NotificationProcessor))]
    public async Task Run([ServiceBusTrigger("Notifications", Connection = "AzureServiceBus")] string rawEvent, Dictionary<string, object> userProperties, FunctionContext context)
    {
        var eventType = userProperties["EventType"].ToString() ?? throw new Exception("Incoming event type is undefined");
        var eventNamePosition = eventType.LastIndexOf('.') + 1;
        var eventName = eventType[eventNamePosition..];

        logger.LogInformation("Processing event of type '{eventName}'...", eventName);
        
        await HandleInvitationProcessStarted(JsonSerializer.Deserialize<InvitationProcessStarted>(rawEvent));
        logger.LogInformation("Completed processing event of type '{eventName}'", eventName);
    }

  async Task HandleInvitationProcessStarted(InvitationProcessStarted message)
    {
        logger.LogInformation("Sending invitation to user {userId} at {email} ...", message.UserId, message.Email);

        var subject = "...";
        var htmlContent = "...";
        var textContent = "...";

        var data = new
        {
            Customer = new
            {
                FirstName = message.UserId,
                LastName = message.UserId,
            },
            ActivationLink = $"{sendgridOptions.ActivationLink}{message.InvitationId}"
        };

        var dynamicTemplate = await emailClient.Templates.CreateAsync("Dynamic invitation template", TemplateType.Dynamic).ConfigureAwait(false);

        await emailClient.Templates.CreateVersionAsync(dynamicTemplate.Id, "Version 1", subject, htmlContent, textContent, true, EditorType.Code, data);

        var to = new MailAddress(message.Email, message.UserId);
        var from = new MailAddress("support@abc.com", "support@abc.com");

        var messageId = await emailClient.Mail.SendToSingleRecipientAsync(to, from, dynamicTemplate.Id, data);

        logger.LogInformation("Invitation sent (message id: {messageId})", messageId);
    }
}
```

**CSPROJ file**

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Label="Functions related properties">
        <AzureFunctionsVersion>v4</AzureFunctionsVersion>
        <OutputType>Exe</OutputType>
        <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="4.2.1" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" OutputItemType="Analyzer" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.6.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
        <PackageReference Include="StrongGrid" Version="0.87.0" />
    </ItemGroup>

    <ItemGroup>
        <None Update="host.json" CopyToOutputDirectory="PreserveNewest" />
        <None Update="local.settings.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Never" />
    </ItemGroup>

</Project>
```

>All this to say, let me know if you can run your code on your own machine. This would help us determine if the problem is localized to Azure functions or not.

I am running this locally (using Azure Functions Runtime/CLI).

I suspect this has to do with the fact that the library is [using .NET 5](https://github.com/Jericho/StrongGrid/blob/87f1138b3bb37b98e492c6604c9bd4027b9fcb53/Source/StrongGrid/StrongGrid.csproj#L4), where my Function is running on .NET 6. The exception message seems to confirm that with 

```
[2022-02-04T07:43:39.960Z] ---> System.Exception: Unable to write a value of type StrongGrid.Models.MailAddress
[2022-02-04T07:43:39.961Z] ---> System.MissingMethodException: Method not found: 'Void System.Text.Json.Serialization.Metadata.JsonObjectInfoValues`1.set_ObjectCreator(System.Func`1<!0>)'.
[2022-02-04T07:43:39.962Z] at StrongGrid.Utilities.StrongGridJsonSerializerContext.get_MailAddress()
```

**Comment by Jericho** [comment]
> I suspect this has to do with the fact that the library is using .NET 5, where my Function is running on .NET 6

That' a very good guess. To prove or disprove your theory, I converted my test app (which I use to send myself a test email) from .NET 5 to .NET 6 and, sure enough, I get the exact same exception: `Method not found: 'Void System.Text.Json.Serialization.Metadata.JsonObjectInfoValues1.set_ObjectCreator(System.Func1<!0>)'`. I proceeded to modify the StrongGrid library to target .NET 6.0 in addition to the other current targets (i.e.: `net5.0`, `netstandard2.1` and `net48`) and it solved the problem. I have published a [beta version of the library with the net6.0 target](https://www.myget.org/feed/jericho/package/nuget/StrongGrid/0.88.0-net6-0056) on my MyGet feed and would appreciate your feedback to confirm it solves the problem for you as well before I release the final version to NuGet.

**Comment by SeanFeldman** [comment]
@Jericho, 0.88.0-preview is working as expected. Good to go 👍

**Comment by Jericho** [comment]
Excellent! Thank you for confirming. I will publish the final 0.88.0 to NuGet. You should see it in the next 30 minutes or so.

Thanks again for alerting me to this problem and for helping me find the solution.

**Comment by SeanFeldman** [comment]
Thank you for such a quick fix, @Jericho.
