### ISSUE TITLE
ProcessedEvent can't be parsed due to Pool ID being a string

### ISSUE THREAD

**Issue by MikeDoesStuff** [Jericho/StrongGrid#454]
> ```
> "pool": {
>             "name": "new_MY_test",
>             "id": 210
>         },
> ```

Not sure how recent of a change this is but now Sendgrid posts the pool ID as a string rather than an Int - this causes an exception when Parsing.

```An unhandled exception has occurred while executing the request.
System.Text.Json.JsonException: The JSON value could not be converted to System.Int64. Path: $.pool.id | LineNumber: 0 | BytePositionInLine: 110.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'String' as a number.
   at System.Text.Json.Utf8JsonReader.TryGetInt64(Int64& value)
   at System.Text.Json.Utf8JsonReader.GetInt64()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)```

_Originally posted by @MikeDoesStuff in https://github.com/Jericho/StrongGrid/issues/314#issuecomment-1165573974_

**Comment by Jericho** [comment]
Are you able to capture a sample of the JSON payload you receive from SendGrid and post it here? This would help me reproduce the problem you are experiencing.

**Comment by MikeDoesStuff** [comment]
Hi I have redacted some information but this is thereabouts what the payload looks like. Hopefully this is of use:
```
[
  {
    "category": [
      "category1",
      "category2",
      "category3"
    ],
    "email": "example@example.com",
    "event": "processed",
    "pool": {
      "id": "111111",
      "name": "poolymcpoolface"
    },
    "send_at": 0,
    "customID": "1b1e2ce2-c5ba-4685-a59e-667a3775684e",
    "sg_event_id": "REDACTED",
    "sg_message_id": "REDACTED",
    "smtp-id": "<REDACTED>",
    "timestamp": 1655917486
  }
]
```
Cheers

**Comment by Jericho** [comment]
The pool id in the payload you provided is indeed a string which contradicts SendGrid's documentation and samples:
![image](https://user-images.githubusercontent.com/112710/175818160-735dda21-6d43-4b50-ba9a-ed648621e7f1.png)

Unfortunately, SendGrid's documentation [GitHub repo](https://github.com/sendgrid/docs/) was `archived` in August last year which means that we can no longer ask questions to get clarification when we notice discrepancies like what you discovered.

Having said that, the JSON payload you provided is clear evidence that the pool identifier is a string no matter what the documentation says so I don't think we need to get confirmation from SendGrid (where would we ask anyway?).

I'll make the correction and publish an update shortly.

**Comment by MikeDoesStuff** [comment]
Thanks for the swift response and fix 👍
