### ISSUE TITLE
 net8.0 support and new nuget package to solve MissingMethodException

### ISSUE THREAD

**Issue by gedefran** [Jericho/StrongGrid#499]
@Jericho any chance you could toss in net8.0 support and publish a new nuget package?

I'm thinking it will fix my issue:
```
System.MissingMethodException: Method not found: 'System.IO.MemoryStream Microsoft.IO.RecyclableMemoryStreamManager.GetStream(System.String)'.
   at HttpMultipartParser.RebufferableBinaryReader.ReadByteLineAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at HttpMultipartParser.RebufferableBinaryReader.ReadByteLineAsync(CancellationToken cancellationToken)
   at HttpMultipartParser.RebufferableBinaryReader.ReadLineAsync(CancellationToken cancellationToken)
   at HttpMultipartParser.StreamingBinaryMultipartFormDataParser.DetectBoundaryAsync(RebufferableBinaryReader reader, CancellationToken cancellationToken)
   at HttpMultipartParser.StreamingBinaryMultipartFormDataParser.RunAsync(CancellationToken cancellationToken)
   at HttpMultipartParser.MultipartFormBinaryDataParser.ParseStreamAsync(Stream stream, String boundary, Encoding encoding, Int32 binaryBufferSize, String[] binaryMimeTypes, Boolean ignoreInvalidParts, CancellationToken cancellationToken)
   at HttpMultipartParser.MultipartFormBinaryDataParser.ParseAsync(Stream stream, String boundary, Encoding encoding, Int32 binaryBufferSize, String[] binaryMimeTypes, Boolean ignoreInvalidParts, CancellationToken cancellationToken)
   at StrongGrid.Utilities.SendGridMultipartFormDataParser.ParseAsync(Stream stream, CancellationToken cancellationToken)
   at StrongGrid.WebhookParser.ParseInboundEmailWebhookAsync(Stream stream, CancellationToken cancellationToken)
```

**Comment by Jericho** [comment]
There must be something other than just net8.0 that's causing this problem because I am able to run all the unit tests (in particular the [InboundEmailAsync](https://github.com/Jericho/StrongGrid/blob/develop/Source/StrongGrid.UnitTests/WebhookParserTests.cs#L434) unit test) under .net 8.0 as can be seen here:
![image](https://github.com/Jericho/StrongGrid/assets/112710/5b24c4c0-ab6a-4024-8051-7d255cda3042)

Is there any additional info you can share about your situation? Any repro steps that would allow me to reproduce the problem?

**Comment by Jericho** [comment]
Found info that is probably relevant to the problem you are experiencing: the release notes of the latest version of the `Microsoft.IO.RecyclableMemoryStreamManager` package (which is 3.0.0) state that methods previously marked as obsolete, such as `RecyclableMemoryStreamManager.GetStream` for example, have been removed (see [here](https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream/blob/018e5c620fe1397e95499b775b428c147053ee54/CHANGES.md?plain=1#L8)). StrongGrid indeed invokes this method so it's perfectly normal that you would get `Method not found` if you are referencing version 3.0.0. However, What's puzzling me is that StrongGrid has a dependency on version 2.3.2, not 3.0.0. 

Is it possible that you have somehow upgraded this package to 3.0.0? Was that intentional?

Before you ask 😜, let me say that I don't intend to upgrade this package's reference in StrongGrid. The reason is that Microsoft has dropped support for .NET framework 4 which StrongGrid still supports.

**Comment by gedefran** [comment]
Thanks for the quick reply, I did indeed have another dependency that brought in version 3.0.0 (luckily it was recalled so everything is great once again).

**Comment by Jericho** [comment]
Glad you were able to resolve this problem but I need to correct something I said: .NET framework 4 has not been dropped from the latest version of the `RecyclableMemoryStream` package as evidenced by this info available on Nuget.org:

![image](https://github.com/Jericho/StrongGrid/assets/112710/4d3cc9e2-7e9b-4814-a6fa-286c9d8829f9)

All this to say that I believe it's safe to upgrade this package in a future release. It's not urgent since you were able to figure out a solution but it's a good idea to proactively make this change to avoid other developers experiencing what you went through yesterday.
